version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
        auth:
          username: singharunk
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false

      # build and push Docker image
      - run: |
          docker build -t singharunk/dev:latest .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push singharunk/dev:latest:latest
